import type { Metadata } from "next";
import { Geist, Geist_Mono, Orbitron , Gravitas_One,Playfair_Display } from "next/font/google";
import "./globals.css";
// import { Orbitron } from "next/font/google";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["700", "800", "900"],
    variable: "--font-playfair",
  display: "swap",
});

const gravitas = Gravitas_One({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-gravitas',
});

const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-orbitron",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} ${gravitas.variable} ${playfair.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
